### ISSUE TITLE
Windows executable is an empty file

### ISSUE THREAD

**Issue by jakubpawlowicz** [bake-bake-bake/bakeware#118]
I ran into another issue with Windows releases: the `mix release` seems to work fine, but the output executable is an empty file. I can see in the logs that the executable is being build and then shrinked from 56 to 20 MB but the output is empty.

I've tried many times, with clean `_build` folder as well.

My environment: Windows 10, Erlang R24, Elixir 1.11.4.

Any ideas? Happy to provide more details.

**Comment by simonmcconnell** [comment]
Can you outline the path you took to build?

**Comment by simonmcconnell** [comment]
So you're running in the Command Prompt under QEMU?  Have you tried compiling any of the examples in this environment?

From looking at [the assembler](https://github.com/bake-bake-bake/bakeware/blob/015f38e11f1aaf1a77105c157eadaaa72e403cb0/lib/bakeware/assembler.ex#L5) I reckon you can disable compression like so:

```elixir
def release do
  [
    demo: [
      bakeware: [
        compress?: false
      ]
    ]
  ]
end
```

**Comment by jakubpawlowicz** [comment]
Thanks @simonmcconnell - I indeed run the standard Command Prompt. Building any app under examples also yield an empty executable file.

Btw, should I give #119 a try?

**Comment by simonmcconnell** [comment]
Yes. I am getting empty executables too on 0.2.1. I didn't test with proper
paths when I changed from `cat` to `type` but #119 rectifies that.

**Comment by jakubpawlowicz** [comment]
Will do, thanks a lot!
