### ISSUE TITLE
Issue when home path contains spaces

### ISSUE THREAD

**Issue by jakubpawlowicz** [bake-bake-bake/bakeware#120]
Hey guys!

I ran into an issue executing a binary when user has spaces in their Windows home path:
https://github.com/bake-bake-bake/bakeware/blob/015f38e11f1aaf1a77105c157eadaaa72e403cb0/lib/bakeware/assembler.ex#L121

I manually fixed it by setting the offending line to `set ROOT="%~dp0"` but I have no idea if that's the proper way of quoting.

**Comment by simonmcconnell** [comment]
@jakubpawlowicz that looks to be the proper way.  I'll include it in #119.
