### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by makeshyft-tom-g** [bake-bake-bake/bakeware#124]
Hi there, sorry if this question is answered somewhere ..... but in the main  description it says that making Windows exe is not yet available, but may be soon.  But then some of the code contains references to windows.
So is this able to be used to build windows exe's yet?

**Comment by simonmcconnell** [comment]
Yep. The instructions are in the readme. That line at the top is outdated

**Comment by jjcarstens** [comment]
Fixed with #125
