### ISSUE TITLE
Running on mobile devices?

### ISSUE THREAD

**Issue by NinoScript** [bake-bake-bake/bakeware#130]
Is it theoretically possible to support running Elixir apps inside Android and iOS with this?

**Comment by fhunleth** [comment]
I don't know of anyone who's done that with Bakeware. I don't know what's involved, so I'm afraid to speculate. Bakeware does require that you build on the platform that you run on (no cross-compilation). That probably will make things harder.

A similar project called [burrito](https://github.com/burrito-elixir/burrito) supports cross-compilation so it might be a step closer.

**Comment by simonmcconnell** [comment]
You can with https://github.com/elixir-desktop/desktop, to some extent, with some elbow grease.
