### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by sergiotapia-papa** [bake-bake-bake/bakeware#37]
Hey this looks really exciting! The reason I use Nim is because I need to have small easy to distribute binaries for my apps.

If I can do this with Elixir, I'll just use Elixir! 

How far away do you think you guys are from Windows support? If you don't even know that answer is helpful to.

**Comment by fhunleth** [comment]
I have a feeling like it's not too far off. I did a test run with mingw, but I didn't have any time last weekend to push any real progress up. It's probably a bunch of small details and writing up docs and I'm hoping to find someone who really likes to work on Windows to help out with it.

**Comment by vans163** [comment]
Windows support would seal the deal.

**Comment by tensor-programming** [comment]
If you guys don't mind, I may poke around and look at what needs to be done to make it compatible with windows mingw and msvc (if that's possible even). Would absolutely be a game changer in my mind if we could create self contained releases on the main platforms for Elixir.

**Comment by fhunleth** [comment]
We definitely don't mind! I think we all got way busier than expected.

Please keep us posted on pain points. We've been shelling out a few places out of conveniences, but it might be time to stop especially if that's a problem for Windows.

**Comment by johns10** [comment]
I think this project is awesome, and I'd also like to see this working with windows. I'm not much of a c programmer but I'd love to help out. 

I've got a browser automation application and I'd like to be able to deploy it locally to run alongside chrome remote interface. This would be the perfect way to deploy a agent, or my entire phoenix application to the local machine.

**Comment by tschnibo** [comment]
Windows support would be awesome :). My point here is, that "deployment" of an elixir application with Docker / Podman is relatively straight forward... of course for client machines the overhead is maybe not ideal (I guess this is why you are pushing this project). But for windows we cannot use this tools therefore I would be very glad to have this toolbox as alternative to self contained python flask applications :+1:
