### ISSUE TITLE
remove bakeware messages

### ISSUE THREAD

**Issue by vans163** [bake-bake-bake/bakeware#46]
When running a packed bin I get
```
./xelnagatemple 
bakeware: starting '/home/user/project/xelnagatemple/xelnagatemple' (cachedir=/home/user/.cache/bakeware)...
bakeware: Running /home/user/.cache/bakeware/7a4000baaf2321b7c6d4ce572697e2fdf3179bd199f04d69fa4c154693073cb4/start...
```

Is it possible to remove the msg?

**Comment by fhunleth** [comment]
Yes, definitely. I keep thinking that the SpawnFest should complete and the repo should open up for us any day now. If not, I'll fork and start making updates like this.

In the mean time, comment out this line: https://github.com/spawnfest/bakeware/blob/main/bakeware/src/bakeware.h#L23

**Comment by vans163** [comment]
> Yes, definitely. I keep thinking that the SpawnFest should complete and the repo should open up for us any day now. If not, I'll fork and start making updates like this.
> 
> In the mean time, comment out this line: https://github.com/spawnfest/bakeware/blob/main/bakeware/src/bakeware.h#L23

All good it doesn't bother me atm, and I understand now that Spawnfest is blocking things, no rush heh.
