### ISSUE TITLE
Bakeware script is called even in dev env and halts vm

### ISSUE THREAD

**Issue by vans163** [bake-bake-bake/bakeware#71]
https://github.com/bake-bake-bake/bakeware/blob/main/lib/bakeware/script.ex

So I am a little lost now but I included https://github.com/xenomorphtech/xelnagatemple into another project and when I run that other project I get 

```
warning: Caught exception in main/1: :error => :function_clause
  (elixir 1.11.1) lib/integer.ex:232: Integer.parse(nil, 10)
  (xelnagatemple 0.1.0) lib/bakeware/script.ex:35: XNT.Bakeware._main/0
  (elixir 1.11.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
  (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```
And it halts.  It seems the module is somehow being evaluated at compile time or something and the using starts the app (no idea why the using is causing app to start), https://github.com/xenomorphtech/xelnagatemple/blob/master/lib/ex_bakeware.ex, even tho there is a conditional set.

**Comment by fhunleth** [comment]
This should be fixed in #66. We'll be pushing a new release out soon-ish.
