### ISSUE TITLE
'Quiet mode' for a Bakeware script

### ISSUE THREAD

**Issue by suprafly** [bake-bake-bake/bakeware#72]
It would be great to be able to suppress the extraction / caching messages when using Bakeware to build CLIs.

I was not able to find an option for this, but it could have missed something.

Thanks!

**Comment by jjcarstens** [comment]
@suprafly Can you specify the version you hare using (or if from `main`)

I believe this was already done with https://github.com/bake-bake-bake/bakeware/commit/99dcbbc7c65e397bdb7fb28c460d26967fc6cb71

**Comment by suprafly** [comment]
Cool! I am on `main`.

**Comment by fhunleth** [comment]
@suprafly Could you run `git remote -v`? I think that you might be pointing to the `spawnfest` github org instead of `bake-bake-bake`.

**Comment by suprafly** [comment]
You are correct,
```
{:bakeware, git: "https://github.com/spawnfest/bakeware"}
```

**Comment by fhunleth** [comment]
Great. We're going to be more actively working on the repository, so just in case we accidentally break the `main` branch, you can always reference the latest hex.pm release using`{:bakeware, "~> 0.1"}`.
